# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1et7L-HCDxh4S7JnWC0XdCe_UksAmUlNH
"""

---

## 🧱 3. `app.py` - Arquivo Principal

```python
import streamlit as st

st.set_page_config(page_title="Dashboard E-commerce", layout="wide")

st.title("🛒 Dashboard de Análise de Vendas - Olist")
st.markdown("Projeto desenvolvido como parte do teste técnico do Programa Trainee Triggo.ai.")

st.sidebar.title("📌 Navegação")
pages = {
    "1. Vendas por Mês e Categoria": "_1_📊_Vendas_por_Mês_e_Categoria",
    "2. Mapa de Vendas por Região": "_2_🗺️_Mapa_de_Vendas_por_Região",
    "3. Avaliação vs Tempo de Entrega": "_3_📈_Avaliação_vs_Entrega",
    "4. Análise de Vendedores": "_4_🧑‍💼_Análise_de_Vendedores"
}

selection = st.sidebar.radio("Ir para:", list(pages.keys()))

page = pages[selection] + ".py"
with open(f"pages/{page}", encoding="utf-8") as f:
    code = compile(f.read(), page, 'exec')
    exec(code)