# -*- coding: utf-8 -*-
"""load_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hLnUmA2XPT3eyKRmFwmw3FFENz5Ipe5f
"""

import pandas as pd
import numpy as np

def load_data():
    # Carregar datasets
    customers = pd.read_csv('data/olist_customers_dataset.csv')
    orders = pd.read_csv('data/olist_orders_dataset.csv')
    order_items = pd.read_csv('data/olist_order_items_dataset.csv')
    products = pd.read_csv('data/olist_products_dataset.csv')
    sellers = pd.read_csv('data/olist_sellers_dataset.csv')
    order_reviews = pd.read_csv('data/olist_order_reviews_dataset.csv')

    # Converter datas
    orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
    orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'], errors='coerce')
    orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

    # Tratar valores nulos
    orders = orders.dropna(subset=['order_delivered_customer_date'])

    # Junção das tabelas
    df = pd.merge(orders, customers, on='customer_id', how='inner')
    df = pd.merge(df, order_items, on='order_id', how='inner')
    df = pd.merge(df, products, on='product_id', how='left')
    df = pd.merge(df, sellers, on='seller_id', how='left')
    df = pd.merge(df, order_reviews[['order_id', 'review_score']], on='order_id', how='left')

    # Calcular tempo de entrega
    df['delivery_days'] = (df['order_delivered_customer_date'] - df['order_purchase_timestamp']).dt.days

    # Definir atraso
    df['delayed'] = (df['order_delivered_customer_date'] > df['order_estimated_delivery_date']).astype(int)

    return df